### ISSUE TITLE
`cssProp` feature produces invalid CSS with object syntax

### ISSUE THREAD

**Issue by amakk** [styled-components/babel-plugin-styled-components#186]
Hi, I'm using the new `css` property, and I noticed that when I upgraded to babel-plugin-styled-components `1.9.2` (from `1.9.0`) it is no longer handling objects in CSS property correctly.

Given this input:

```html
<div css={{ color: 'red' }}>Test</div>
```

I am getting this output: 
```css
.kIHpqD{-webkit-undefinedcolor:red;-ms-flex-undefinedcolor:red;undefinedcolor:red;-webkit-undefined;-ms-flex-undefined;undefined;}
```
and further down: 
```javascript
<div class="my-page___StyledDiv-sc-1f0w8lp-3 kIHpqD">Test</div>
```

I'm expecting it to output the css as something like: 
```css
.kIHpqD{color:red;}
```

If it helps, I'm using `styled-components 4.1.2` with Gatsby via `gatsby-plugin-styled-components 3.0.4`
