### ISSUE TITLE
Possible bug with minification

### ISSUE THREAD

**Issue by huy-nguyen** [styled-components/babel-plugin-styled-components#56]
I ran into this strange problem today which I think has to do with minification done by the plugin. I was trying to compile this TypeScript file (note the missing semicolon at the end of the template literal). This plugin is applied together with other babel plugins after the typescript compilation step in webpack.

```ts
import * as styledComponents from 'styled-components';
const styled = styledComponents.default;

const contentLeft = 'globalContentLeft';
const contentRight = 'globalContentRight';
const globalContentTop = 'globalContentTop';
const globalContentBottom = 'globalContentBottom';

const menuTop = 'rankingsMenuTop';
const menuBottom = 'rankingsMenuBottom';
const contentTop = 'rankingsMenuContentTop';
const contentBottom = 'rankingsMenuContentBottom';

const Grid = styled.main`
  grid-column: ${contentLeft} / ${contentRight};
  grid-row: ${globalContentTop} / ${globalContentBottom};

  display: grid;
  grid-template-rows: [${menuTop}] 250px
                      [${menuBottom} ${contentTop}] auto
                      [${contentBottom}]
`;

export default Grid;
```
If I leave minification on (default), this is the eventual style tag injected into the DOM. Note the missing `grid-template-rows` CSS property:
```css
.kMCkPy {
  grid-column: globalContentLeft / globalContentRight;
  grid-row: globalContentTop / globalContentBottom;
  display: grid;
}
```
If I set `minify: false`, I get the expected output with the `grid-template-rows` property:
```css

.jXSKOK {
  grid-column: globalContentLeft / globalContentRight;
  grid-row: globalContentTop / globalContentBottom;
  display: grid;
  grid-template-rows: [rankingsMenuTop] 250px [rankingsMenuBottom rankingsMenuContentTop] auto [rankingsMenuContentBottom];
}
```
However, if I turn minification back on but also insert the missing semicolon at the end of the template literal, I get the expected output.
```css

.cZjrpn {
  grid-column: globalContentLeft / globalContentRight;
  grid-row: globalContentTop / globalContentBottom;
  display: grid;
  grid-template-rows: [rankingsMenuTop] 250px[rankingsMenuBottom rankingsMenuContentTop] auto[rankingsMenuContentBottom];
}
```
I used `styled-components` v 2.0.1 and `babel-plugin-styled-components` v 1.1.4.
